### ISSUE TITLE
Come up with a better animation for the home page (blog)

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/flare#1]
Our blog currently has this animation that looks like stars that cluster around the cursor. Try it here: https://blog.khoj.dev. Replace this with something better, ideally interactive, that renders nicely. The issue with the current one is that the clustering logic is kinda glitchy and also it looks jank.

**Comment by vr-varad** [comment]
Hey @sabaimran I would like to work on this issue as I have worked on issues like this in my projects.
It would be helpful If you could provide me with what you want so that I could start working on this as soon as possible.

**Comment by sabaimran** [comment]
Hey @vr-varad , shoot me an email at saba@khoj.dev ! Would be helpful if you can link me to any of your past samples.

**Comment by sabaimran** [comment]
Hey @vr-varad , shoot me an email at saba@khoj.dev ! Would be helpful if you can link me to any of your past samples.

**Comment by vr-varad** [comment]
They were local ;) But I could create some show it up, how about this? @sabaimran

**Comment by sabaimran** [comment]
Sure! Anything that you think highlights your work. Send it on yo
***@***.*** :)

**Comment by vr-varad** [comment]
@sabaimran made some bg designs https://tsparticle-example.vercel.app/.
let me know if you want to ask something.
